USE [master];
GO

CREATE LOGIN [DOTNETAPP] FROM EXTERNAL PROVIDER
 WITH OBJECT_ID='APP_MSI_OBJECT_ID_PLACEHOLDER'

CREATE USER [DOTNETAPP_USER] FOR LOGIN [DOTNETAPP] WITH DEFAULT_SCHEMA=[dbo];
ALTER ROLE db_datareader ADD MEMBER [DOTNETAPP_USER];

ALTER ROLE [db_ddladmin] ADD MEMBER [DOTNETAPP_USER];